bootdo:
  uploadPath: D:/var/uploaded_files/
logging:
  level:
    root: info
    com.bootdo: debug
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/platformweb-mysql?useUnicode=true&characterEncoding=utf8
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
          initialSize: 1
          minIdle: 3
          maxActive: 20
          # 配置获取连接等待超时的时间
          maxWait: 60000
          # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          timeBetweenEvictionRunsMillis: 60000
          # 配置一个连接在池中最小生存的时间，单位是毫秒
          minEvictableIdleTimeMillis: 30000
          
          #hsqldb	select 1 from INFORMATION_SCHEMA.SYSTEM_USERS
          #Oracle	select 1 from dual
          #DB2	select 1 from sysibm.sysdummy1
          #MySql	select 1
          #Microsoft SqlServer	select1
          #postgresql	select version()
          #ingres	select 1
          #derby	values 1
          #H2	select1
          #mysql
          #validationQuery: select 'x'
          validationQuery: select 1
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          # 打开PSCache，并且指定每个连接上PSCache的大小
          poolPreparedStatements: true
          maxPoolPreparedStatementPerConnectionSize: 20
          # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
          filters: stat,wall,slf4j
          # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
          connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
          # 合并多个DruidDataSource的监控数据
          #useGlobalDataSourceStat: true
        slave_1:
          url: jdbc:mysql://localhost:3306/lawapp_tc?useUnicode=true&characterEncoding=utf8
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
          initialSize: 1
          minIdle: 3
          maxActive: 20
          # 配置获取连接等待超时的时间
          maxWait: 60000
          # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          timeBetweenEvictionRunsMillis: 60000
          # 配置一个连接在池中最小生存的时间，单位是毫秒
          minEvictableIdleTimeMillis: 30000
          
          #hsqldb	select 1 from INFORMATION_SCHEMA.SYSTEM_USERS
          #Oracle	select 1 from dual
          #DB2	select 1 from sysibm.sysdummy1
          #MySql	select 1
          #Microsoft SqlServer	select1
          #postgresql	select version()
          #ingres	select 1
          #derby	values 1
          #H2	select1
          #mysql
          #validationQuery: select 'x'
          validationQuery: select 1
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          # 打开PSCache，并且指定每个连接上PSCache的大小
          poolPreparedStatements: true
          maxPoolPreparedStatementPerConnectionSize: 20
          # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
          filters: stat,wall,slf4j
          # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
          connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
          # 合并多个DruidDataSource的监控数据
          #useGlobalDataSourceStat: tru
        slave_2:
          url: jdbc:oracle:thin:@127.0.0.1:1521/xe
          username: PLATFORMWEB
          password: 123456
          driver-class-name: oracle.jdbc.driver.OracleDriver # 3.2.0开始支持SPI可省略此配置
          initialSize: 1
          minIdle: 3
          maxActive: 20
          # 配置获取连接等待超时的时间
          maxWait: 60000
          # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          timeBetweenEvictionRunsMillis: 60000
          # 配置一个连接在池中最小生存的时间，单位是毫秒
          minEvictableIdleTimeMillis: 30000
          
          #hsqldb	select 1 from INFORMATION_SCHEMA.SYSTEM_USERS
          #Oracle	select 1 from dual
          #DB2	select 1 from sysibm.sysdummy1
          #MySql	select 1
          #Microsoft SqlServer	select1
          #postgresql	select version()
          #ingres	select 1
          #derby	values 1
          #H2	select1
          #mysql
          #validationQuery: select 'x'
          validationQuery: select 1 from dual
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          # 打开PSCache，并且指定每个连接上PSCache的大小
          poolPreparedStatements: true
          maxPoolPreparedStatementPerConnectionSize: 20
          # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
          filters: stat,wall,slf4j
          # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
          connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
          # 合并多个DruidDataSource的监控数据
          #useGlobalDataSourceStat: true
  redis:
      host: localhost
      port: 6379
      password:
      # 连接超时时间（毫秒）
      timeout: 10000
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1